# Generated by Django 5.2.17 on 2026-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallazgo', models.CharField(max_length=250)),
                ('accion', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'capa',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('responsable', models.CharField(max_length=150)),
                ('participantes', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Programada', max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'capacitaciones',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Vigente', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documentos',
                'ordering': ['-fecha_creacion', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=120)),
                ('responsable', models.CharField(max_length=150)),
                ('estado', models.CharField(default='Abierto', max_length=50)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'hallazgos',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=120)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(default='Usuario', max_length=80)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['nombre'],
            },
        ),
    ]
