# Generated by Django 5.2.17 on 2026-09-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_documento_archivo_documento_fecha_subida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Gestor de calidad', 'Gestor de calidad'), ('Consulta', 'Consulta')], default='Consulta', max_length=80),
        ),
    ]
