# Generated by Django 5.2.17 on 2026-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Analista', 'Analista'), ('Consultor', 'Consultor')], default='Consultor', max_length=80),
        ),
    ]
